export  const  menu=[
    {
        icon:"iconfont icon-选课",
        name:"个人中心",
        router:"/UserCenter",
        id:"1",
        subItem:[
            {
                id:"1-1",
                name:"账户信息",
                router:""
            },
            {
                id:"1-2",
                name:"隐私设置",
                router:""
            }
        ]
    },
    {
        icon:"el-icon-video-camera",
        name:"视频中心",
        id:"2",
        router:"/UserCenter",
        subItem:[
            {
                id:"/uploadVideo",
                name:"上传视频",
                router:""
            },
            {
                id:"/videoPlayer",
                name:"我的视频",
                router:""

            }
        ]
    },
    {
        icon:"el-icon-s-comment",
        name:"消息中心",
        router:"/UserCenter",
        id:"3",
        subItem:[
            {
                id:"3-1",
                name:"未收消息",
                router:""
            },
            {
                id:"3-2",
                name:"垃圾信箱",
                router:""

            }
        ]
    }
]