  export const ManyCourses=
      [{
          courseId: 12343,
          courseName: '逻辑与幽默',
          courseType: '沟通与管理',
          courseHours: 32,
          courseCredit: 2,
          capacity: 180,
          courseCollege: '新闻学院',
          teacherName: "黄仁卓",
          teacherTitle: "副教授",
          courseWeek: "4-11",
          courseTime: "周三9-12",
          courseLocation: "东九" ,
      },
  {
      courseId: 12343,
      courseName: '营养与健康',
      courseType: '沟通与管理',
      courseHours: 32,
      courseCredit: 2,
      capacity: 180,
      courseCollege: '新闻学院',
      teacherName: "黄仁卓",
      teacherTitle: "副教授",
      courseWeek: "4-11",
      courseTime: "周三9-12",
      courseLocation: "东久",
  }, {
          courseId: 12343,
      courseName: '食品安全与卫生',
          courseType: '沟通与管理',
          courseHours: 32,
          courseCredit: 2,
          capacity: 180,
          courseCollege: '新闻学院',
          teacherName: "黄仁卓",
          teacherTitle: "副教授",
          courseWeek: "4-11",
          courseTime: "周三9-12",
          courseLocation: "东久",
  }, {
          courseId: 12343,
      courseName: '深度中国',
          courseType: '沟通与管理',
          courseHours: 32,
          courseCredit: 2,
          capacity: 180,
          courseCollege: '新闻学院',
          teacherName: "黄仁卓",
          teacherTitle: "副教授",
          courseWeek: "4-11",
          courseTime: "周三9-12",
          courseLocation: "东久",
  },
          {
              courseId: 12343,
              courseName: '民国历史人物',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseId: 12343,
              courseName: '晚清历史人物研究',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseId: 12343,
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '黄仁卓',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseId: 12343,
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          }, {
          courseName: '111111',
          courseType: '沟通与管理',
          courseHours: 32,
          courseCredit: 2,
          capacity: 180,
          courseCollege: '新闻学院',
          teacherName: "黄仁卓",
          teacherTitle: "副教授",
          courseWeek: "4-11",
          courseTime: "周三9-12",
          courseLocation: "东久",
      }, {
          courseName: '逻辑与幽默',
          courseType: '沟通与管理',
          courseHours: 32,
          courseCredit: 2,
          capacity: 180,
          courseCollege: '新闻学院',
          teacherName: "黄仁卓",
          teacherTitle: "副教授",
          courseWeek: "4-11",
          courseTime: "周三9-12",
          courseLocation: "东久",
      },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          },
          {
              courseName: '逻辑与幽默',
              courseType: '沟通与管理',
              courseHours: 32,
              courseCredit: 2,
              capacity: 180,
              courseCollege: '新闻学院',
              teacherName: "黄仁卓",
              teacherTitle: "副教授",
              courseWeek: "4-11",
              courseTime: "周三9-12",
              courseLocation: "东久",
          }]


